<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SQCD_8005AGV_Simulator.AutomationTests</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\SQCD_8005AGV_Simulator.AutomationHost\SQCD_8005AGV_Simulator.AutomationHost.csproj" />
    <ProjectReference Include="..\..\src\SQCD_8005AGV_Simulator.Core\SQCD_8005AGV_Simulator.Core.csproj" />
  </ItemGroup>
</Project>
