<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>SQCD_8005AGV_Simulator</AssemblyName>
    <RootNamespace>SQCD_8005AGV_Simulator</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\SQCD_8005AGV_Simulator.Core\SQCD_8005AGV_Simulator.Core.csproj" />
    <ProjectReference Include="..\SQCD_8005AGV_Simulator.AutomationHost\SQCD_8005AGV_Simulator.AutomationHost.csproj" />
    <None Include="simulator.settings.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
